### ISSUE TITLE
我想加一些功能

### ISSUE THREAD

**Issue by dcy10000** [noahziheng/ssr-helper#12]
想在docker下实现多开
我想到的方案是，
1.从config.json中，把default属性移植出来（因为多开要共用一个config.json）放入单独的一个json中,比如default-server.json.
2.不依赖于default.json(每次start根据default-server.json的名字,找到对应的server,然后和local.json动态生成default.json).这样方便,lazy load,配置也不方便.

这些我能写,可能引入一些bug.不知道这个提议的怎么样.可以的话,我就改了

**Comment by noahziheng** [comment]
Hi dcy10000,
1. 首先，对本项目设计初衷主要是针对终端用户，采用交互方式，并未针对纯的 *nix Shell 应用进行考虑，在 Docker 下应用可能存在阻塞问题，Docker 本身也并不适合这种场景，性能和实用性都存疑。
2. 其次，有关多开，你是希望实现负载均衡？亦或在不同场景下使用不同代理？个人认为可以通过在 sslocal 的调用上下一些功夫，Docker 在这一场景下可能存在各种问题，欢迎针对这一 Feature 提出 PR。
3. 你提出的方案中，个人比较赞同，也有计划在下一大版本中加以优化的方式是方式2，实现思路有轻微差异。我的想法是，将现有 config 中 servers 段改为 Object，其 key 为 Hash 值，default 段存放选中服务器信息的 Hash 值，直接调用。如果你有兴趣，欢迎协助我完成这一实现。
4. 如果你对 helper 这一小项目有兴趣，十分欢迎加入维护，因个人工作原因，目前新 Feature 和项目进一步优化、增加场景的工作进度很慢。

Thanks for feedback,
Noah

**Comment by dcy10000** [comment]
1.我对docker的性能充满信心.从https://www.jianshu.com/p/ad5bc1874976
还有类似文章可以看出，docker除了启动稍慢,正常运行时的损耗可以说小于5%，微乎其微。要说性能，真该操心是python，还有害怕计算的node.js.
docker的实用性我也算满意,status可以查看状态,即使开机启动,down命令也可以直接关闭,不用像大部分程序要ps | grep 再kill.
2.不是为了负载均衡,我介绍一下,是多个连接,监听不同的本地端口,配合omega使用.
简单来说,是搭配omega实现根据不同的域名走不同的线路,这样不用为了看视频特地切换线路.
而装在宿主机里,多个helper配置文件冲突了,所以,我的想法是装在docker里,不过确实不怎么理想.docker build不是交互式的终端.所以我想直接拿配置文件开刀.
3.不是很懂为啥要hash.hash 的意义在哪里
不可以这样吗
![image](https://user-images.githubusercontent.com/26567055/36575510-4f995dea-1886-11e8-843c-9b65568643ec.png)
直接用名字.这样依旧可以定位到server啊,也可以查重.这个功能我可以写一下.
4.说一说有啥新功能,我看看有没有兴趣.

**Comment by noahziheng** [comment]
谢谢参与，回应如下：
1. Docker 在运算性能方面的表现确实令人满意，但在本场景下多层 NAT 后的网络性能存疑，远没有在宿主机端清晰可控。
2. 了解，参见 1、3。
3. 原因在于兼容同地址多端口使用场景下保证 key 唯一，且能够兼容中文的服务器备注名和组名，你的方案主要问题就是服务器名或组名在于中文时应该会存在性能和兼容问题？
4. 现阶段在计划表内的主要是切换 port 到 ssr-libev 获得更好的跨平台性能和实现服务器列表测速，其余暂无，您对开源项目维护经验丰富？或是大厂大佬？

Noah

**Comment by dcy10000** [comment]
我是个菜鸟,哈哈.
1.默认模式损失10%~20%的吞吐量,并不是不可以接受(300m的网卡表示用不完).另外极致性能可以--net=host,ss默认只处理本地的连接,所以我觉得这个情况下host模式没有安全问题.
3.中文确实可能引入bug,我以前没有用过中文当key,既然不确定能避免就避免.中文到不会造成性能损失,无非就是中文略微长.
你说的对,我确实忘了考虑同名字,地址或端口不同的情况.这样的话,你的思路比较好,不过hash用base6
4代替比较好.

关于配置文件,首先配置文件只影响开启的速度,其次一个人通常没有超过100个server,在这种时候,即使是o(n*n),普通计算机也能在小于0.1秒算出来,我认为不存在性能上的忧虑.

你是要支持路由器吗,不是的话,感觉使用ssr-libev作为底层实现,完全没必要,python完全够用了.另外ssr-libev下架了,要自己根据系统装不同的依赖,然后自己编译,这个对linux小白并不友好.服务器测速,这个...可能有点难写,感觉也不推荐,想要测速,一个server至少五秒,全部测完要好几分钟.建议是加入测试服务器延迟而不是速度.

**Comment by noahziheng** [comment]
同菜鸡😀
 1. 个人仍对在个人环境中使用容器管理连接相关事务这一方法持怀疑态度，所以暂不会进一步研究和支持，如果你的尝试成功欢迎将 Docker Image  纳入进来~
 2. Hash 是为了锁定特征，Base64 只是编码，该冲突的依旧冲突，没意义。中文 key 主要是防兼容问题，性能问题不考虑，要不然我也不会提出 Hash 方案了，Hash 性能占用量更大，不过只是在 add 和 update 的时候计算。
 3. 前面已经有好几起 issue 报的反馈都是 ssr-python 的锅，只是在寻找替代品，ssr-python 也是下架状态，而且 manyuser 分支并不好找就是了。想法是无视掉路径和具体实现，直接使用 `/usr/local/bin/ss-local`。
 4. 表述分歧，此处测速 === 延迟检测。

Noah

**Comment by dcy10000** [comment]
我想了下，既然utf-8情况下，value可以用中文，那key也是可以用中文的。这个应该没区别。
我的想法是这样。
![image](https://user-images.githubusercontent.com/26567055/36631317-afa94b52-19b0-11e8-9ddd-c9901220a0b7.png)
![image](https://user-images.githubusercontent.com/26567055/36631319-b5557a26-19b0-11e8-810e-0865ef0abe46.png)
根据组名，路线名，index，三维属性来定位一个路线。
唯一的缺点是，update会触发小范围的查重，性能略差，但肯定比现在的写法好太多。
另外遍历数组比遍历对象快的多。这是一大优势


routename指的是你写的remark，叫法不同
你的意见不同的话，麻烦截个图，我不太理解你的想法。

**Comment by noahziheng** [comment]
抱歉，最近比较忙，今天才仔细确认了一下你的问题，测速 PR 已合并并新发布版本 `1.1.0`。

1. 有关服务器配置的问题，目前通过自编的 select 模块可以在完成选择回调后锁定服务器，在 connect 时动态生成 default 配置，定位并不成为主要问题。
2. 这一配置一方面是为了完成从存储的配置和本地默认配置进行融合转换，另一主要方面是 `ss-local` 这一命令要求显式提供连接配置文件路径并作为每次运行时完成各种 action 时的配置。所以这一步骤和文件并不能省略。
3. 有关你在 Docker 内的应用，我的建议是其实可以增加选项在 connect 时指定生成或直接使用的 default.json 配置的名称和路径，通过 volume 映射进容器使用。这既能利用交互界面，又能减小对项目的兼容性影响。

你的意见是？或者如果你已有实现，欢迎提交。
Noah

**Comment by dcy10000** [comment]
发现conf太坑了,rename的方法和数据卷挂载文件冲突了.只能采取你说的指定文件的方式了

我写好了功能,通过加option的方式实现的.

大概使用方法如下

### 初始化

1. 下载项目和docker和docker-compose
2. 拷贝预先准备的config.json到config目录(数据卷)下,修改订阅连接为自己的链接
3. 项目根目录运行docker-compose up ssr-update  .更新订阅

### 创建一个新连接

1. config目录下创建json比如ssr1.json,设置三个字段,分别是group.remark和local_port,这里采取一个极端且大众的配置,那就是认为group和remarks确定的时候,对应的server只有一个.因为这样才能在被墙的时候准确的更换ip.如果机场不采用这种方案,我认为那就是机场不人性化了.
2. dockr-compose.yml加入一个服务.照抄前面就行,只要有两处名字改为ssr1
3. 运行docker-compose up ssr1 ssr2 ssr3...就可以了,会通过配置生成临时文件连接.\
4. .默认是不关闭就会一直开机自启.

你看看好不好,好的话,我就发pr了.另外请尽快打包进npm,我不会打包,这样我可以优化一下image的大小.

**Comment by noahziheng** [comment]
可以的，只要你测试通过且没覆盖原有的用法和功能就可以提出PR。

Noah
