### ISSUE TITLE
订阅更新问题

### ISSUE THREAD

**Issue by WangPei0316** [noahziheng/ssr-helper#16]
这几次使用发现订阅节点更新后，如果还是相同的会自动覆盖，有新增的会添加，但是之前不能用的不会自动删除。
有没有什么好的解决方案能去除过期节点呢(或者说是我不会用)？

**Comment by noahziheng** [comment]
Hello WangPei0316,
   这是设计时的考虑，避免多个订阅地址指向同一分组时造成误删。
   建议运行 `ssr delay`（需更新到最新版本）进行测速，如发现节点不可用，使用 `ssr rm` 命令删除，未来可能考虑自动化该过程。

Thanks for feedback,
Noah
