### ISSUE TITLE
请问能否通过多线程计算ssr delay呀？

### ISSUE THREAD

**Issue by lihk11** [noahziheng/ssr-helper#19]
非常感谢作者提供这么好用的工具，极大提高了大家的工作效率！

如果订阅里边服务器数量较多的话，使用ssr delay 就要等很久才能测试完毕，不知道能不能添加多线程计算时延呢？

**Comment by noahziheng** [comment]
Hi lihk11,
Node.js 基于 V8，本质是单线程的，实现多线程需要使用一些较 Hack 的方法来做，我暂时没有时间研究并上线这一能力。
如你有兴趣，欢迎PR～
