### ISSUE TITLE
请问是不是没解析协议参数和混淆参数？

### ISSUE THREAD

**Issue by dingfengshi** [noahziheng/ssr-helper#2]
订阅解析的参数都是乱码。。

**Comment by noahziheng** [comment]
Hello sssste,
        因为个人没有实例使用该两项参数，所以没有实测过该部分解析代码，能否提供一些日志和错误详情供修复参考。

Thanks for issue.

**Comment by dingfengshi** [comment]
Hello，
就是解析到的订阅里，服务器的其他信息是正确的，但是协议参数和混淆参数这两项似乎是没解析出来，是一串大写字母的样子。

**Comment by noahziheng** [comment]
Hello sssste,
能否提供一下解析出现问题的SSR URI，可先将ssr://后的部分base64解码，隐去您的个人服务器信息后重新编码。
Thanks for issue.

**Comment by dingfengshi** [comment]
解码后前一部分相关的数据就是这样的。。然后结果显示的就是＝号后的内容，但实际上混淆参数是"go.twitch.tv"<obfsparam=Z28udHdpdGNoLnR2&protoparam=MTM1MTpLYnIzcng&remark.......

**Comment by dingfengshi** [comment]
似乎再解一次码就能出来了。。

**Comment by noahziheng** [comment]
已发新版本 ssr-helper@1.0.7，增加了对这两个参数的base64解析，请测试其工作是否正常有效，欢迎继续反馈～
