### ISSUE TITLE
/usr/bin/python: can't open file '～/shadowsocksr/shadowsocks/local.py': [Errno 2] No such file or directory Error: Script execute failed!/usr/bin/python: can't open file '～/shadowsocksr/shadowsocks/local.py': [Errno 2] No such file or directory Error: Script execute failed!

### ISSUE THREAD

**Issue by Bl0omZ** [noahziheng/ssr-helper#22]
打不开local文件

**Comment by Bl0omZ** [comment]
/usr/bin/python: can't open file '～/shadowsocksr/shadowsocks/local.py': [Errno 2] No such file or directory
Error: Script execute failed!

**Comment by AlphaGoMK** [comment]
I got the same issue, but it seems that my `ssr-path` is  undefined. Did you solve this problem? Any advice will be appreciated :)

**Comment by an-lee** [comment]
`～/shadowsocksr/shadowsocks/local.py` should be `~/shadowsocksr/shadowsocks/local.py`

**Comment by wanghenshui** [comment]
https://github.com/noahziheng/ssr-helper/blob/6de8190e4e3875504e63a97284abbab7ab45b2ac/lib/exec.js#L19

https://github.com/noahziheng/ssr-helper/blob/dc8a9b6f11083365a922f0fdd2afec74e7c0d523/bin/ssr-config.js#L8

need `ssr config path` to set at first,
for me is
```bash
set config /usr/local/lib/python3.8/dist-packages/
```
