### ISSUE TITLE
ERROR: found an error in config.json: chr() arg not in range(256)

### ISSUE THREAD

**Issue by gogobody** [noahziheng/ssr-helper#3]
ssr connect 的时候
ERROR: found an error in config.json: chr() arg not in range(256)
IPv6 support
Error: Script execute failed!
请问这个如何解决呢

**Comment by noahziheng** [comment]
Hello gogobody,
请尝试运行 `cat ~/.config/ssr-helper-nodejs/default.json` 和 `cat ~/.config/ssr-helper-nodejs/config.json`，并将内容附上（可隐去密码和端口）

谢谢支持～
Noah

**Comment by gogobody** [comment]
default.json
`{
	"server": "la.1.52ll.org",
	"server_port": *,
	"password": "*",
	"method": "aes-128-cfb",
	"obfs": "http_simple",
	"protocol": "auth_sha1_v4",
	"protoparam": "",
	"obfs_param": "/�,",
	"local_address": "127.0.0.1",
	"local_port": 1080,
	"timeout": 300,
	"workers": 1
}`
config.json
`{
{
			"server": "kr.1.52ll.org",
			"server_port": *,
			"password": "*",
			"method": "aes-128-cfb",
			"obfs": "http_simple",
			"protocol": "auth_sha1_v4",
			"group": "ssr",
			"obfsparam": "/�,",
			"protoparam": "",
			"remarks": "[韩SK] [2.0] [移联电]"
		}
	],
	"default": [
		"ssr",
		"[美1] [0.5] [移联电]"
	],
	"subscribe": [
		"*******"
	],
	"ssr-path": "/home/javascript/programs/shadowsocksr"
}`

**Comment by gogobody** [comment]
手动改掉这个参数之后可以了

**Comment by noahziheng** [comment]
已确认应是obfs参数解析的BUG，您的服务商是否配置了混淆参数？能否提供一下原始的SSR URI经base64解码后的原文（同样可隐去密码端口等）供检查问题？
