### ISSUE TITLE
如果能够支持负载均衡就好了

### ISSUE THREAD

**Issue by neofung** [noahziheng/ssr-helper#3]
手上有好几个服务器

**Comment by noahziheng** [comment]
这个属于它核心脚本的内容了，CLI基于Node.js，只管理配置，不直接接触连接，可以向上游的[shadowsocksr-backup/shadowsocksr](https://github.com/shadowsocksr-backup/shadowsocksr)或者[shadowsocksrr/shadowsocksr分支](https://github.com/shadowsocksrr/shadowsocksr)提
