### ISSUE TITLE
订阅的混淆参数及协议参数解析问题

### ISSUE THREAD

**Issue by liolok** [noahziheng/ssr-helper#4]
"obfsparam": "C�;",
			"protoparam": "C�;",

> _原始的SSR URI经base64解码后的原文（同样可隐去密码端口等）_

请问这个怎么操作?

**Comment by noahziheng** [comment]
你是通过订阅获取的地址还是手动添加的？

**Comment by liolok** [comment]
订阅解析的, 其实用helper主要就是为了订阅功能.

**Comment by liolok** [comment]
我应该怎么提交反馈信息?

**Comment by noahziheng** [comment]
因为Github上公开SSR服务器信息过于不安全，能否请单将订阅地址发到我的邮箱noahgaocn@outlook.com，以便我寻找问题成因。

**Comment by noahziheng** [comment]
Moved from #3
