### ISSUE TITLE
You need install python for the script!

### ISSUE THREAD

**Issue by superboy-zjc** [noahziheng/ssr-helper#41]
系统有python环境，不知道为什么会报这个错误

**Comment by dolmens** [comment]
确定有python吗，在终端执行下python看下

**Comment by superboy-zjc** [comment]
> 
> 
> 确定有python吗，在终端执行下python看下

确认有的，已经解决了。是因为项目目录下的exec.js里有一个对python环境的检查，是判断shell中能否找到`python`可执行文件的变量，而阿里云20.3的Ubuntu默认没有名为python的可执行文件，都是python3.8、python2，报了一个`You need install python for the script!`的错误，在/usr/bin下软链接一个python3.8名为python即可。
