### ISSUE TITLE
servers undefined

### ISSUE THREAD

**Issue by vipcxj** [noahziheng/ssr-helper#5]
无法add
(node:65146) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'push' of undefined
无法ls，无法connect，因此也无法start
以上都由于servers变量未定义。

**Comment by noahziheng** [comment]
Hello,
最新的1.0.3版本已修复问题，重新运行安装或使用`yarn global upgrade`或者`npm -g update`更新即可

**Comment by vipcxj** [comment]
修复好快~
