### ISSUE TITLE
SSR连接成功，但无法FQ。

### ISSUE THREAD

**Issue by handbye** [noahziheng/ssr-helper#7]
SSR START 提示已经连接成功。
但是SSR status的时候提示：
`hand@hand:~$ ssr status
SSR Python Client Status: Running
PID:5358
Current: [Ungrouped](jp.jpnode.zihaoc.tk:59607)
✖ Connection test failed!
`
确定配置是正确的，在win下就可以正常使用。

**Comment by noahziheng** [comment]
Hello handbye,
1. 建议使用 `yarn global upgrade` 或 `npm install -g ssr-helper` 升级到最新版本后重新添加配置。
2. 如仍不能工作，请使用 `ssr ls` 和 `ssr edit` 修改配置，检查是否有多余的空格或者乱码，修改后重新 `ssr connect` 。

Thanks for feedback,
Noah
